debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: gom
    password: 134679sd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false # osiv (open seesion in view)
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always # (resource/data.sql)
  data.rest:
    base-path: /api
    detection-strategy: annotated # api auto creating (when it's annotated)
  # user-defined property
  # 해당 프로젝트에 /src/main/java/com.fastcampus.projectboard/config/ThymeleafConfig에 정의됨
  thymeleaf3.decoupled-logic: true

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
